name: E2E Tests

on:
  push:
    branches: [ main, v5, develop ]
  pull_request:
    branches: [ main, v5, develop ]
  workflow_dispatch: # Allow manual trigger

env:
  NODE_VERSION: '20.x'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
      fail-fast: false # Continue testing other browsers even if one fails

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npx cypress verify

      - name: Build application
        run: npm run build:development

      - name: Start application server
        run: |
          npm start &
          sleep 30 # Wait for server to start
        env:
          CI: true

      - name: Wait for application to be ready
        run: |
          npx wait-on http://localhost:4200 --timeout 120000

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          install: false # Already installed
          start: npm start
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 120
          browser: ${{ matrix.browser }}
          spec: |
            cypress/e2e/auth-flow.cy.ts
            cypress/e2e/error-handling.cy.ts
            cypress/e2e/theme-switching.cy.ts
          config: video=true,screenshotOnRunFailure=true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-artifacts-${{ matrix.browser }}
          path: |
            cypress/videos
            cypress/screenshots
          retention-days: 7

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results-${{ matrix.browser }}
          path: |
            cypress/reports
          retention-days: 30

  # Job to check if all E2E tests passed
  e2e-summary:
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: always()
    
    steps:
      - name: Check E2E test results
        run: |
          if [[ "${{ needs.e2e-tests.result }}" == "failure" ]]; then
            echo "❌ E2E tests failed"
            exit 1
          elif [[ "${{ needs.e2e-tests.result }}" == "cancelled" ]]; then
            echo "⚠️ E2E tests were cancelled"
            exit 1
          else
            echo "✅ All E2E tests passed"
          fi

  # Optional: Deploy to staging after successful E2E tests
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    if: github.ref == 'refs/heads/develop' && success()
    
    steps:
      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment"
          # Add deployment commands here