name: Front CI

on:
  push:
    paths: ['front/**','docs/**','.github/workflows/front-ci.yml']
  pull_request:
    paths: ['front/**','docs/**','.github/workflows/front-ci.yml']

jobs:
  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests (Jest)
        run: npm run test:ci

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage
          path: front/coverage

      - name: Build
        run: npm run build

      - name: Build Storybook
        run: npm run build:storybook

      - name: Upload Storybook
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: front/storybook-static
