name: Front CI

on:
  push:
    paths: ['front/**','docs/**','.github/workflows/front-ci.yml']
  pull_request:
    paths: ['front/**','docs/**','.github/workflows/front-ci.yml']

jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'

      - name: Install deps
        run: npm ci

      - name: Install Cypress binary
        run: npx cypress install

      - name: E2E run (Chrome headless)
        uses: cypress-io/github-action@v6
        with:
          working-directory: front
          start: npm run start
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 180
          browser: chrome
          headless: true
          install: false
          command: npm run cypress:run:ci
        env:
          CI: true

      - name: Upload videos on fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: front/cypress/videos

      - name: Upload screenshots on fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: front/cypress/screenshots

  front:
    runs-on: ubuntu-latest
    needs: e2e
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests (Jest)
        run: npm run test:auth

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage
          path: front/coverage

      - name: Build
        run: npm run build

      - name: Build Storybook
        run: npm run build:storybook

      - name: Upload Storybook
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: front/storybook-static
