name: Sync Shared Docs to Frontend

# Trigger: cuando hay push a v5 con cambios en docs/shared/
on:
  push:
    branches: [ v5 ]
    paths:
      - 'docs/shared/**'
      - 'docs/backend/**'

jobs:
  sync:
    # IMPORTANTE: Solo ejecutar si el commit NO contiene 'docs-sync:' (anti-bucle)
    if: ${{ !contains(github.event.head_commit.message, 'docs-sync:') }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout source repo (Backend)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para obtener historial completo

      - name: 🚀 Push shared docs to frontend repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_SYNC }}
        with:
          source-directory: 'docs/shared'
          destination-github-username: '<OWNER>'
          destination-repository-name: 'boukii-admin-panel'
          target-branch: 'v5'
          destination-directory: 'docs/shared'
          commit-message: 'docs-sync: mirror shared docs from backend → frontend'
          user-name: 'boukii-docs-sync-bot'
          user-email: 'noreply@boukii.com'

      - name: 🚀 Push backend docs to frontend repo
        if: ${{ false }}
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_SYNC }}
        with:
          source-directory: 'docs/backend'
          destination-github-username: '<OWNER>'
          destination-repository-name: 'boukii-admin-panel'
          target-branch: 'v5'
          destination-directory: 'docs/backend'
          commit-message: 'docs-sync: mirror backend docs from backend → frontend'
          user-name: 'boukii-docs-sync-bot'
          user-email: 'noreply@boukii.com'
